version: '3'

services:
  clickhouse:
    build:
      context: ./deploy/clickhouse
      dockerfile: Dockerfile
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "9000:9000"

  email_generator:
    build:
      context: ./email-generator/src
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
