version: '3'
include:
  - ./nodes/postgresql.node.yml
  - ./nodes/mongodb.node.yml
  - ./nodes/rabbitmq.yml
services:
#  notifications:
#    build:
#      context: ./notifications/src
#      dockerfile: Dockerfile
#    env_file:
#      - ./notifications/src/.env.fastapi
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mongodb
#    volumes:
#      - /tmp/logs/notifications:/var/log/notifications/app.json

  auth:
    build:
      context: ./mock-auth-service/src
      dockerfile: Dockerfile
    env_file:
      - ./mock-auth-service/src/.env.fastapi
    ports:
      - "8001:8000"
    depends_on:
      - postgresql
    volumes:
      - /tmp/logs/auth:/var/log/auth/app.json

#  nginx:
#    image: nginx:1.19.2
#    volumes:
#      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
#      - /tmp/logs/nginx/:/var/log/nginx
#    depends_on:
#      - notifications
#      - auth
#    ports:
#      - "8080:80"
