version: '3'
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - ../.env.rabbitmq
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq

volumes:
  rabbitmq_data:
