version: '3'

services:
  clickhouse:
#    image: bitnami/clickhouse:23
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "8123:8123"
#    volumes:
#      - ./data/:/docker-entrypoint-initdb.d/
